spring.application.name=ueims_backend
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ueims_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
server.port=8080

app.base-url=http://localhost:5173
app.seed.default-password=Password@123
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

jwt.signerKey=${JWT_SECRET:}
jwt.valid-duration=900
jwt.refreshable-duration=604800

google.client-id=${GOOGLE_CLIENT_ID:}

# Mail Configuration (For Forgot Password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Request Log Configuration
app.request-log.retention-days=7
app.request-log.file-retention-days=14

# Auto-generate SQL schema file on application startup
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=../SQL/generated_schema.sql
spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
