const fs = require('fs');
const path = require('path');

const filePath = path.join('c:', 'FPT', 'SWP391', 'ueims', 'UEIMS_Project', 'ueims_frontend', 'src', 'pages', 'student', 'tabs', 'ProfileTab.tsx');

let content = fs.readFileSync(filePath, 'utf-8');
let lines = content.split(/\\r?\\n/);

const cvViewIndex = lines.findIndex(l => l.includes('// ── CV View'));
const topHalf = lines.slice(0, cvViewIndex);
while (topHalf.length > 0 && (topHalf[topHalf.length - 1].trim() === '};' || topHalf[topHalf.length - 1].trim() === ');' || topHalf[topHalf.length - 1].trim() === '</>' || topHalf[topHalf.length - 1].trim() === ')' || topHalf[topHalf.length - 1].trim() === '</Modal>')) {
  topHalf.pop();
}

const bottomHalfStr = [
  "    {/* Bio & Social Links Section */}",
  "    <NeuSurface style={{ padding: 24, marginTop: 16 }}>",
  "      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>",
  "        <h3 style={{ fontSize: 15, fontWeight: 700, color: cc.text, margin: 0 }}>About & Links</h3>",
  "      </div>",
  "      <div style={{ marginBottom: 16 }}>",
  "        <p style={{ fontSize: 12, fontWeight: 600, color: cc.textMuted, margin: '0 0 4px' }}>Bio</p>",
  "        <p style={{ fontSize: 13, color: cc.text, margin: 0, whiteSpace: 'pre-wrap' }}>{profile.bio || 'No bio provided.'}</p>",
  "      </div>",
  "      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>",
  "        {profile.linkedinUrl && (",
  "          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>",
  "            <span style={{ fontSize: 12, fontWeight: 600, color: cc.textMuted, width: 80 }}>LinkedIn:</span>",
  "            <a href={profile.linkedinUrl} target=\"_blank\" rel=\"noopener noreferrer\" style={{ fontSize: 13, color: cc.primary }}>{profile.linkedinUrl}</a>",
  "          </div>",
  "        )}",
  "        {profile.githubUrl && (",
  "          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>",
  "            <span style={{ fontSize: 12, fontWeight: 600, color: cc.textMuted, width: 80 }}>GitHub:</span>",
  "            <a href={profile.githubUrl} target=\"_blank\" rel=\"noopener noreferrer\" style={{ fontSize: 13, color: cc.primary }}>{profile.githubUrl}</a>",
  "          </div>",
  "        )}",
  "        {profile.portfolioUrl && (",
  "          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>",
  "            <span style={{ fontSize: 12, fontWeight: 600, color: cc.textMuted, width: 80 }}>Portfolio:</span>",
  "            <a href={profile.portfolioUrl} target=\"_blank\" rel=\"noopener noreferrer\" style={{ fontSize: 13, color: cc.primary }}>{profile.portfolioUrl}</a>",
  "          </div>",
  "        )}",
  "      </div>",
  "    </NeuSurface>",
  "",
  "    <Modal",
  "      title=\"Edit Profile\"",
  "      open={isEditing}",
  "      onCancel={() => setIsEditing(false)}",
  "      footer={null}",
  "      destroyOnClose",
  "    >",
  "      <Form",
  "        form={form}",
  "        layout=\"vertical\"",
  "        initialValues={{",
  "          major: profile?.major,",
  "          skills: profile?.skills,",
  "          bio: profile?.bio,",
  "          linkedinUrl: profile?.linkedinUrl,",
  "          githubUrl: profile?.githubUrl,",
  "          portfolioUrl: profile?.portfolioUrl",
  "        }}",
  "        onFinish={handleUpdate}",
  "      >",
  "        <Form.Item name=\"major\" label=\"Major\">",
  "          <Input placeholder=\"e.g. Software Engineering\" />",
  "        </Form.Item>",
  "        <Form.Item name=\"skills\" label=\"Skills (comma separated)\">",
  "          <Input placeholder=\"e.g. Java, React, Node.js\" />",
  "        </Form.Item>",
  "        <Form.Item name=\"bio\" label=\"Bio\">",
  "          <Input.TextArea rows={3} placeholder=\"Tell us about yourself...\" />",
  "        </Form.Item>",
  "        <Form.Item name=\"linkedinUrl\" label=\"LinkedIn URL\">",
  "          <Input placeholder=\"https://linkedin.com/in/...\" />",
  "        </Form.Item>",
  "        <Form.Item name=\"githubUrl\" label=\"GitHub URL\">",
  "          <Input placeholder=\"https://github.com/...\" />",
  "        </Form.Item>",
  "        <Form.Item name=\"portfolioUrl\" label=\"Portfolio URL\">",
  "          <Input placeholder=\"https://...\" />",
  "        </Form.Item>",
  "        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 24 }}>",
  "          <CTAButton variant=\"ghost\" onClick={(e) => { e?.preventDefault(); setIsEditing(false); }}>Cancel</CTAButton>",
  "          <CTAButton variant=\"primary\" loading={loading} onClick={() => form.submit()}>Save Changes</CTAButton>",
  "        </div>",
  "      </Form>",
  "    </Modal>",
  "  </>",
  "  );",
  "};",
  "",
  "// ── CV View ───────────────────────────────────────────────────────────────────",
  "const CvView: React.FC<{ cvUrl?: string; cvFileName?: string; onRefresh: () => void }> = ({ cvUrl, cvFileName, onRefresh }) => {",
  "  const [uploading, setUploading] = useState(false);",
  "  const [dragActive, setDragActive] = useState(false);",
  "  const [cvFile, setCvFile] = useState<File | null>(null);",
  "  const [showUpload, setShowUpload] = useState(false);",
  "",
  "  const validateFile = (file: File): string | null => {",
  "    if (file.type !== 'application/pdf') return 'Only PDF files are accepted!';",
  "    if (file.size > 5 * 1024 * 1024) return 'CV file must not exceed 5MB!';",
  "    return null;",
  "  };",
  "",
  "  const handleDrop = (e: React.DragEvent) => {",
  "    e.preventDefault();",
  "    setDragActive(false);",
  "    const file = e.dataTransfer.files?.[0];",
  "    if (file) {",
  "      const error = validateFile(file);",
  "      if (error) { message.error(error); return; }",
  "      setCvFile(file);",
  "    }",
  "  };",
  "",
  "  const handleUpload = async () => {",
  "    if (!cvFile) return;",
  "    try {",
  "      setUploading(true);",
  "      const fd = new FormData();",
  "      fd.append('file', cvFile);",
  "      await StudentProfileService.uploadCV(fd);",
  "      message.success('CV uploaded successfully!');",
  "      setCvFile(null);",
  "      setShowUpload(false);",
  "      onRefresh();",
  "    } catch (err: any) {",
  "      message.error(err.response?.data?.message || 'Upload failed!');",
  "    } finally {",
  "      setUploading(false);",
  "    }",
  "  };",
  "",
  "  const handleDelete = async () => {",
  "    try {",
  "      setUploading(true);",
  "      await StudentProfileService.deleteCV();",
  "      message.success('CV deleted successfully!');",
  "      onRefresh();",
  "    } catch (err: any) {",
  "      message.error(err.response?.data?.message || 'Delete failed!');",
  "    } finally {",
  "      setUploading(false);",
  "    }",
  "  };",
  "",
  "  const displayName = cvFileName || (cvUrl ? cvUrl.split('_').slice(2).join('_').replace('/uploads/cv/', '') : 'CV Document');",
  "",
  "  if (!cvUrl && !showUpload) {",
  "    return (",
  "      <NeuSurface style={{ padding: 24 }}>",
  "        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20 }}>",
  "          <div style={{ width: 44, height: 44, borderRadius: cc.radiusMd, background: '#dbeafe', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#3b82f6' }}>",
  "            <FileTextOutlined style={{ fontSize: 20 }} />",
  "          </div>",
  "          <div>",
  "            <h3 style={{ fontSize: 15, fontWeight: 600, color: cc.text, margin: 0 }}>My CVs</h3>",
  "            <p style={{ fontSize: 12, color: cc.textMuted, margin: '2px 0 0' }}>PDF format only, max 5MB</p>",
  "          </div>",
  "        </div>",
  "        <div",
  "          onDragEnter={(e) => { e.preventDefault(); setDragActive(true); }}",
  "          onDragLeave={() => setDragActive(false)}",
  "          onDragOver={(e) => e.preventDefault()}",
  "          onDrop={handleDrop}",
  "          onClick={() => document.getElementById('cv-upload-input')?.click()}",
  "          style={{",
  "            border: `2px dashed ${dragActive ? cc.primary : cc.border}`,",
  "            borderRadius: cc.radiusLg, padding: '48px 24px', textAlign: 'center',",
  "            background: dragActive ? cc.primaryMuted : cc.bgLight,",
  "            transition: 'all 0.2s ease', cursor: 'pointer',",
  "          }}",
  "        >",
  "          <input id=\"cv-upload-input\" type=\"file\" accept=\".pdf\" style={{ display: 'none' }}",
  "            onChange={(e) => {",
  "              const f = e.target.files?.[0];",
  "              if (f) { const err = validateFile(f); if (err) message.error(err); else { setCvFile(f); setShowUpload(true); } }",
  "            }}",
  "          />",
  "          <div style={{ width: 56, height: 56, borderRadius: cc.radiusMd, background: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px', boxShadow: '0 2px 8px rgba(0,0,0,.08)' }}>",
  "            <svg width=\"28\" height=\"28\" viewBox=\"0 0 24 24\" fill=\"none\" stroke={cc.primary} strokeWidth=\"2\" strokeLinecap=\"round\" strokeLinejoin=\"round\">",
  "              <path d=\"M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z\"/>",
  "              <polyline points=\"14 2 14 8 20 8\"/>",
  "              <line x1=\"12\" y1=\"18\" x2=\"12\" y2=\"12\"/>",
  "              <line x1=\"9\" y1=\"15\" x2=\"15\" y2=\"15\"/>",
  "            </svg>",
  "          </div>",
  "          <p style={{ fontSize: 15, fontWeight: 700, color: cc.text, margin: '0 0 4px' }}>Drop your CV here</p>",
  "          <p style={{ fontSize: 12, color: cc.textMuted, margin: 0 }}>or click to browse &mdash; PDF only, max 5MB</p>",
  "        </div>",
  "      </NeuSurface>",
  "    );",
  "  }",
  "",
  "  return (",
  "    <NeuSurface style={{ padding: 24 }}>",
  "      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 }}>",
  "        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>",
  "          <div style={{ width: 44, height: 44, borderRadius: cc.radiusMd, background: '#dbeafe', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#3b82f6' }}>",
  "            <FileTextOutlined style={{ fontSize: 20 }} />",
  "          </div>",
  "          <div>",
  "            <h3 style={{ fontSize: 15, fontWeight: 600, color: cc.text, margin: 0 }}>My CVs</h3>",
  "            <p style={{ fontSize: 12, color: cc.textMuted, margin: '2px 0 0' }}>Only one CV is allowed &mdash; uploading a new file replaces the current one</p>",
  "          </div>",
  "        </div>",
  "        {!showUpload && (",
  "          <CTAButton variant=\"primary\" size=\"sm\" icon={<PlusOutlined />} onClick={() => setShowUpload(true)}>Upload</CTAButton>",
  "        )}",
  "      </div>",
  "",
  "      {/* Current CV card */}",
  "      {cvUrl && !showUpload && (",
  "        <div style={{ background: cc.surface, border: `1px solid ${cc.border}`, borderRadius: cc.radiusLg, padding: 20, display: 'flex', alignItems: 'center', gap: 16 }}>",
  "          <div style={{ width: 48, height: 48, borderRadius: cc.radiusMd, background: cc.primaryMuted, display: 'flex', alignItems: 'center', justifyContent: 'center', color: cc.primary, flexShrink: 0 }}>",
  "            <FileTextOutlined style={{ fontSize: 22 }} />",
  "          </div>",
  "          <div style={{ flex: 1, minWidth: 0 }}>",
  "            <p style={{ fontSize: 14, fontWeight: 700, color: cc.text, margin: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{displayName}</p>",
  "            <p style={{ fontSize: 12, color: cc.textMuted, margin: '3px 0 0' }}>Uploaded CV</p>",
  "          </div>",
  "          <div style={{ display: 'flex', gap: 8, flexShrink: 0 }}>",
  "            <CTAButton variant=\"ghost\" size=\"sm\" icon={<EyeOutlined />} onClick={() => window.open(resolveFileUrl(cvUrl), '_blank')}>View</CTAButton>",
  "            <CTAButton variant=\"danger\" size=\"sm\" icon={<svg width=\"12\" height=\"12\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" strokeWidth=\"2.5\" strokeLinecap=\"round\"><polyline points=\"3 6 5 6 21 6\"/><path d=\"M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6\"/><path d=\"M10 11v6\"/><path d=\"M14 11v6\"/></svg>} onClick={handleDelete} loading={uploading}>Delete</CTAButton>",
  "          </div>",
  "        </div>",
  "      )}",
  "",
  "      {/* Upload panel */}",
  "      {showUpload && (",
  "        <div style={{ background: cc.bgLight, border: `1px solid ${cc.border}`, borderRadius: cc.radiusLg, padding: 24 }}>",
  "          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>",
  "            <h4 style={{ fontSize: 14, fontWeight: 700, color: cc.text, margin: 0 }}>Upload New CV</h4>",
  "            <button onClick={() => { setShowUpload(false); setCvFile(null); }} style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 18, color: cc.textMuted, padding: 0 }}>&#x2715;</button>",
  "          </div>",
  "",
  "          <div",
  "            onDragEnter={(e) => { e.preventDefault(); setDragActive(true); }}",
  "            onDragLeave={() => setDragActive(false)}",
  "            onDragOver={(e) => e.preventDefault()}",
  "            onDrop={handleDrop}",
  "            onClick={() => document.getElementById('cv-upload-input-2')?.click()}",
  "            style={{",
  "              border: `2px dashed ${dragActive ? cc.primary : cc.border}`,",
  "              borderRadius: cc.radiusMd, padding: '28px 16px', textAlign: 'center',",
  "              background: dragActive ? cc.primaryMuted : '#fff',",
  "              transition: 'all 0.2s ease', cursor: 'pointer', marginBottom: 16,",
  "            }}",
  "          >",
  "            <input id=\"cv-upload-input-2\" type=\"file\" accept=\".pdf\" style={{ display: 'none' }}",
  "              onChange={(e) => {",
  "                const f = e.target.files?.[0];",
  "                if (f) { const err = validateFile(f); if (err) message.error(err); else setCvFile(f); }",
  "              }}",
  "            />",
  "            {cvFile ? (",
  "              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 12 }}>",
  "                <FileTextOutlined style={{ fontSize: 28, color: cc.success }} />",
  "                <div style={{ textAlign: 'left' }}>",
  "                  <p style={{ fontSize: 14, fontWeight: 600, color: cc.text, margin: 0 }}>{cvFile.name}</p>",
  "                  <p style={{ fontSize: 12, color: cc.textMuted, margin: '2px 0 0' }}>{(cvFile.size / 1024 / 1024).toFixed(2)} MB</p>",
  "                </div>",
  "              </div>",
  "            ) : (",
  "              <>",
  "                <UploadOutlined style={{ fontSize: 32, color: cc.textMuted, marginBottom: 8, display: 'block' }} />",
  "                <p style={{ fontSize: 13, fontWeight: 600, color: cc.text, margin: '0 0 2px' }}>Drop file here or click to browse</p>",
  "                <p style={{ fontSize: 11, color: cc.textMuted, margin: 0 }}>PDF only, max 5MB</p>",
  "              </>",
  "            )}",
  "          </div>",
  "",
  "          <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end' }}>",
  "            <CTAButton variant=\"ghost\" onClick={() => { setShowUpload(false); setCvFile(null); }}>Cancel</CTAButton>",
  "            <CTAButton variant=\"primary\" icon={<UploadOutlined />} onClick={handleUpload} loading={uploading} disabled={!cvFile}>Upload</CTAButton>",
  "          </div>",
  "        </div>",
  "      )}",
  "",
  "      {cvUrl && !showUpload && (",
  "        <p style={{ fontSize: 11, color: cc.textMuted, marginTop: 12, textAlign: 'center' }}>",
  "          To replace your CV, click the <strong>Upload</strong> button above.",
  "        </p>",
  "      )}",
  "    </NeuSurface>",
  "  );",
  "};",
  "",
  "// ── Main ProfileTab ───────────────────────────────────────────────────────────",
  "export const ProfileTab: React.FC = () => {",
  "  const [profile, setProfile] = useState<MyProfile | null>(null);",
  "  const [loading, setLoading] = useState(true);",
  "  const [activeView, setActiveView] = useState<ProfileView>('profile');",
  "",
  "  useEffect(() => { fetchProfile(); }, []);",
  "",
  "  const fetchProfile = async () => {",
  "    try {",
  "      setLoading(true);",
  "      const res = await StudentProfileService.getMyProfile();",
  "      const data = res?.data?.result;",
  "      if (!data) { console.warn('Unable to fetch profile data'); return; }",
  "      setProfile(data);",
  "    } catch (err) {",
  "      console.error('Failed to fetch profile', err);",
  "    } finally {",
  "      setLoading(false);",
  "    }",
  "  };",
  "",
  "  if (loading) {",
  "    return <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: 400 }}><Spin size=\"large\" /></div>;",
  "  }",
  "",
  "  if (!profile) {",
  "    return <div style={{ textAlign: 'center', padding: 40, color: cc.textMuted }}>Unable to load profile data.</div>;",
  "  }",
  "",
  "  return (",
  "    <div style={{ maxWidth: 800, margin: '0 auto', padding: '0 24px 40px', fontFamily: 'Inter, sans-serif' }}>",
  "      {/* Tab Switcher */}",
  "      <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 24 }}>",
  "        <TabSwitcher active={activeView} onChange={setActiveView} />",
  "      </div>",
  "",
  "      {/* Views */}",
  "      {activeView === 'profile' ? (",
  "        <ProfileInfoView profile={profile} onRefresh={fetchProfile} />",
  "      ) : (",
  "        <CvView",
  "          cvUrl={profile.cvUrl}",
  "          cvFileName={profile.cvFileName}",
  "          onRefresh={fetchProfile}",
  "        />",
  "      )}",
  "    </div>",
  "  );",
  "};"
];

fs.writeFileSync(filePath, topHalf.join('\n') + '\n' + bottomHalfStr.join('\n'));
console.log('Restored ProfileTab successfully!');
